name: Linting

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      # Python & poetry setup
      #----------------------------------------------
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction --with dev
  
      #----------------------------------------------

    - name: Run linter
      run: |
        poetry run lint

