name: Install & Test Python App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      # Python setup
      #----------------------------------------------
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'poetry'

      #----------------------------------------------
      # poetry
      #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install --no-interaction
  
      #----------------------------------------------
      # run tests
      #----------------------------------------------
    - name: Run tests
      run: |
        poetry run test
